In [2]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
natural_numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(natural_numbers)


[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
zeros_matrix = np.zeros((3, 3))
print(zeros_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [5]:
random_matrix = np.random.randint(1, 11, size=(5, 5))
print(random_matrix)

[[10  6  4  1  6]
 [ 5  9  3  3  6]
 [ 6  4  9  9  7]
 [ 6 10  3  5 10]
 [ 6 10  6  9  1]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [6]:
random_real_matrix = np.random.rand(4, 4)
print(random_real_matrix)

[[0.59755709 0.44400479 0.40474143 0.67455599]
 [0.105644   0.99101756 0.30641469 0.30290077]
 [0.43899513 0.12139851 0.99018688 0.8848605 ]
 [0.91438549 0.19346316 0.43965168 0.12704037]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [7]:
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise Addition:", addition_result)
print("Element-wise Subtraction:", subtraction_result)
print("Element-wise Multiplication:", multiplication_result)

Array 1: [1 4 5 4 3]
Array 2: [4 3 2 5 1]
Element-wise Addition: [5 7 7 9 4]
Element-wise Subtraction: [-3  1  3 -1  2]
Element-wise Multiplication: [ 4 12 10 20  3]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [8]:
vector1 = np.array([2, 4, 6, 8, 10, 12, 14])
vector2 = np.array([1, 3, 5, 7, 9, 11, 13])
# Calculate the scalar product (dot product)
scalar_product = np.dot(vector1, vector2)
# Output the original vectors and their scalar product
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Scalar Product:", scalar_product)

Vector 1: [ 2  4  6  8 10 12 14]
Vector 2: [ 1  3  5  7  9 11 13]
Scalar Product: 504


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [9]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))
result_matrix = np.dot(matrix1, matrix2)
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nResult of Matrix Multiplication:")
print(result_matrix)

Matrix 1:
[[4 5]
 [4 4]]

Matrix 2:
[[10  3  6]
 [ 9  9  9]]

Result of Matrix Multiplication:
[[85 57 69]
 [76 48 60]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [10]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original Matrix:")
print(matrix)
# Calculate the inverse of the matrix
try:
    inverse_matrix = np.linalg.inv(matrix)
    print("\nInverse Matrix:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nMatrix is singular, and its inverse does not exist.")

Original Matrix:
[[ 1  3 10]
 [10 10 10]
 [ 2  9  7]]

Inverse Matrix:
[[-0.03773585  0.13018868 -0.13207547]
 [-0.09433962 -0.0245283   0.16981132]
 [ 0.13207547 -0.00566038 -0.03773585]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [11]:
matrix = np.random.rand(4, 4)
print("Original Matrix:")
print(matrix)
transposed_matrix = np.transpose(matrix)
print("\nTransposed Matrix:")
print(transposed_matrix)

Original Matrix:
[[0.4173364  0.46557727 0.63077264 0.93519162]
 [0.74539095 0.58883155 0.30808004 0.87952113]
 [0.28774831 0.85611499 0.68838102 0.80249001]
 [0.93108345 0.28274514 0.50694584 0.43846654]]

Transposed Matrix:
[[0.4173364  0.74539095 0.28774831 0.93108345]
 [0.46557727 0.58883155 0.85611499 0.28274514]
 [0.63077264 0.30808004 0.68838102 0.50694584]
 [0.93519162 0.87952113 0.80249001 0.43846654]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [12]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
result_vector = np.dot(matrix, vector)
print("\nResult of Matrix-Vector Multiplication:")
print(result_vector)

Matrix:
[[ 6  9  7  5]
 [ 7  3  4  3]
 [ 3 10  5  2]]

Vector:
[2 9 7 3]

Result of Matrix-Vector Multiplication:
[157  78 137]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [13]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)
print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
result_vector = np.dot(matrix, vector)
print("\nResult of Matrix-Vector Multiplication:")
print(result_vector)

Matrix:
[[0.57824574 0.11409294 0.83426229]
 [0.90348219 0.06931388 0.28396888]]

Vector:
[0.52805458 0.28998626 0.58261737]

Result of Matrix-Vector Multiplication:
[0.8244864  0.66263319]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [14]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
result_matrix = np.multiply(matrix1, matrix2)
print("\nResult of Element-wise Multiplication:")
print(result_matrix)

Matrix 1:
[[3 3]
 [6 6]]

Matrix 2:
[[8 3]
 [7 4]]

Result of Element-wise Multiplication:
[[24  9]
 [42 24]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [16]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
result_matrix = np.divide(matrix1, matrix2)
print("\nResult of Matrix Divide:")
print(result_matrix)

Matrix 1:
[[5 3]
 [5 1]]

Matrix 2:
[[6 2]
 [4 1]]

Result of Matrix Divide:
[[0.83333333 1.5       ]
 [1.25       1.        ]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [17]:
matrix = np.random.randint(1, 101, size=(5, 5))
print("Matrix:")
print(matrix)
matrix_sum = np.sum(matrix)
print("\nSum of Matrix Elements:", matrix_sum)

Matrix:
[[ 94   4  62  79  86]
 [ 28  51  28  59   4]
 [ 93  94  27  24  89]
 [ 61 100  86   9  15]
 [ 62  94  43  43  45]]

Sum of Matrix Elements: 1380


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [18]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
result_matrix = matrix1 - matrix2
print("\nResult of Matrix Subtraction:")
print(result_matrix)

Matrix 1:
[[ 7 10  3 10]
 [ 2  1  1  6]
 [ 5  4  9  3]
 [ 7 10  4  1]]

Matrix 2:
[[ 1  4  8  2]
 [ 3  3  8  1]
 [ 1  1  3 10]
 [ 4  3  4 10]]

Result of Matrix Subtraction:
[[ 6  6 -5  8]
 [-1 -2 -7  5]
 [ 4  3  6 -7]
 [ 3  7  0 -9]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [19]:
matrix = np.random.rand(3, 3)
print("Matrix:")
print(matrix)
row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(-1, 1)
print("\nColumn Vector of Row Sums:")
print(column_vector)

Matrix:
[[0.58586146 0.74950554 0.61561335]
 [0.27838278 0.21397473 0.86278776]
 [0.96892831 0.46599684 0.36181193]]

Column Vector of Row Sums:
[[1.95098036]
 [1.35514526]
 [1.79673708]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [20]:
original_matrix = np.random.randint(low=1, high=10, size=(3, 4))
print("Original Matrix:")
print(original_matrix)
squared_matrix = np.square(original_matrix)
print("\nMatrix of Squares:")
print(squared_matrix)

Original Matrix:
[[2 5 9 4]
 [9 1 1 6]
 [1 1 4 6]]

Matrix of Squares:
[[ 4 25 81 16]
 [81  1  1 36]
 [ 1  1 16 36]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [21]:
original_vector = np.random.randint(1, 51, size=4)
print("Original Vector:")
print(original_vector)
sqrt_vector = np.sqrt(original_vector)
print("\nSquare Root Vector:")
print(sqrt_vector)
print("\n")


Original Vector:
[21 33 49 12]

Square Root Vector:
[4.58257569 5.74456265 7.         3.46410162]


